# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainW(object):
    def setupUi(self, MainW):
        MainW.setObjectName("MainW")
        MainW.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainW)
        self.centralwidget.setObjectName("centralwidget")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.button.setObjectName("button")
        MainW.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainW)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainW.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainW)
        self.statusbar.setObjectName("statusbar")
        MainW.setStatusBar(self.statusbar)

        self.retranslateUi(MainW)
        QtCore.QMetaObject.connectSlotsByName(MainW)

    def retranslateUi(self, MainW):
        _translate = QtCore.QCoreApplication.translate
        MainW.setWindowTitle(_translate("MainW", "YellowC"))
        self.button.setText(_translate("MainW", "PushButton"))
